const TrackerActionTypes = {
    TOGGLE_TRACKER_HIDDEN: 'TOGGLE_TRACKER_HIDDEN',    
    ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE: 'ADD_ITEM_FAILURE',
    CLEAR_ITEM_FROM_LIST: 'CLEAR_ITEM_FROM_LIST',
    FETCH_TRACKERS_START: 'FETCH_TRACKERS_START',
    FETCH_TRACKERS_SUCCESS: 'FETCH_TRACKERS_SUCCESS',
    FETCH_TRACKERS_FAILURE: 'FETCH_TRACKERS_FAILURE'
};
export default TrackerActionTypes;